# Generated by Django 5.1.6 on 2025-02-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestNSI',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('title_all', models.CharField(max_length=255)),
                ('title_correct', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('weight', models.SmallIntegerField(blank=True, null=True)),
                ('lead_hand', models.CharField(blank=True, max_length=255, null=True)),
                ('diseases', models.CharField(blank=True, max_length=255, null=True)),
                ('smoking', models.BooleanField(blank=True, null=True)),
                ('alcohol', models.CharField(blank=True, max_length=255, null=True)),
                ('sport', models.CharField(blank=True, max_length=255, null=True)),
                ('insomnia', models.BooleanField(blank=True, null=True)),
                ('current_health', models.SmallIntegerField(blank=True, null=True)),
                ('gaming', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('try_number', models.SmallIntegerField()),
                ('number_all_answers', models.IntegerField(blank=True, null=True)),
                ('number_correct_answers', models.IntegerField(blank=True, null=True)),
                ('complete_time', models.DurationField(blank=True, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitive.testnsi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitive.user')),
            ],
        ),
    ]
