# Generated by Django 5.1.6 on 2025-02-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='accuracy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='complete_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='number_all_answers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='number_correct_answers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='try_number',
            field=models.CharField(max_length=10),
        ),
    ]
