# Generated by Django 5.1.6 on 2025-02-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0002_alter_testresult_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
