# Generated by Django 5.1.6 on 2025-02-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0003_alter_testresult_complete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_count', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitive.testnsi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitive.user')),
            ],
            options={
                'unique_together': {('user', 'test')},
            },
        ),
    ]
